site_name: Mansur
site_description: 'Documentation for the Mansur project, including the mansurPlugins library'
site_author: 'Assaf Ben Zur'


markdown_extensions:
      - fontawesome_markdown
      - admonition
theme: 
  name: material
  logo: 'images/mansur_logo_noText.png'
  icon: 'images/mansur_logo_noText.png'
  favicon: 'images/mansur_logo_noText.png'
  palette:
    primary: 'grey'
    accent: 'grey'
  feature:
      tabs: true
  text: 'Ubuntu'
  code: 'Ubuntu Mono'
plugins:
    - search
extra:
  social:
    - type: 'github'
      link: 'https://github.com/asaf-b'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCMjNlJjSxIam--3u87oh5PQ'
    - type: 'twitter'
      link: 'https://twitter.com/mansurRig'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/asaf-ben-zur/'
    - type: 'imdb'
      link: 'https://www.imdb.com/name/nm8262040/?ref_=nv_sr_3'
    
nav:
    - index.md
    - About:
      - about.md
    - Getting Started:
      - installation.md
    - Support-Us:
      - Support-Us.md
    - Code Documentation:
      - Maya-Plugins.md
      - mansur:
        - core:
          - arguments.md
          - globals.md
          - log.md
          - nodes.md
          - prefixSuffix.md
          - skinUtils.md
          - string.md
          - UIUtils.md
          - utility.md
        - globalUtils:
          - defSearch:
            - defSearch.md
          - logViewer:
            - logviewer.md
          - dynUI.md
        - adminUtils:
          - documentationBuild:
            - docBuildMansur.md
          - pluginRelease:
            - pluginRelease.md
          - productRelease:
            - install:
              - install.md
            - productRelease.md
          - userManagement:
            - userManagement.md
        - block:
          - core:
            - blockUtility.md
            - buildModules.md
            - controlShapes.md
          - modules:
            - character_body:
              - FKChain:
                - FKChain.md
              - foot:
                - foot.md
              - freeControl:
                - freeControl.md
              - limb:
                - limb.md
              - lookAtControl:
                - lookAtControl.md
              - meta:
                - meta.md
              - simpleSquash:
                - simpleSquash.md
          - picker:
            - picker.md
            - plgSettings.md
          - blockBuildUI.md
extra_css:
    - extra.css

