site_name: Mansur
site_description: 'Documentation for the Mansur project, including the mansurPlugins library'
site_author: 'Assaf Ben Zur'


markdown_extensions:
      - fontawesome_markdown
theme: 
  name: material
  logo: 'images/mansur_01.png'
  favicon: 'images/mansur_01.png'
  palette:
    primary: 'blue-grey'
    accent: 'indigo'
  feature:
      tabs: true
plugins:
    - search
extra:
  social:
    - type: 'github'
      link: 'https://github.com/asaf-b'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCMjNlJjSxIam--3u87oh5PQ'
    - type: 'twitter'
      link: 'https://twitter.com/mansurRig'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/asaf-ben-zur/'
    - type: 'imdb'
      link: 'https://www.imdb.com/name/nm8262040/?ref_=nv_sr_3'
    
nav:
    - index.md
    - Getting Started:
      - installation.md
    - About:
      - about.md
    - Support-Us:
      - supportUs.md
    - Developers Guide:
      - devGuide.md
    - Documentation:
      - mansur:
        - core:
          - arguments.md
          - globals.md
          - log.md
          - nodes.md
          - prefixSuffix.md
          - settingsGlobals.md
          - string.md
          - UIUtils.md
          - utility.md
        - globalUtils:
          - defSearch:
            - defSearch.md
          - logViewer:
            - logviewer.md
          - dynUI.md
        - adminUtils:
          - documentationBuild:
            - docBuildMansur.md
          - pluginRelease:
            - pluginRelease.md
        - block:
          - core:
            - blockUtility.md
            - buildModules.md
            - controlShapes.md
          - modules:
            - dev:
              - FKChain:
                - FKChain.md
              - foot:
                - foot_construction.md
                - foot_customGuides.md
              - freeControl:
                - freeControl.md
          - picker:
            - picker.md
          - blockBuildUI.md
extra_css:
    - extra.css

