site_name: 'Mansur-Rig Docs'
site_description: 'Documentation for the Mansur project, including the mansurPlugins library'
site_author: 'Assaf Ben Zur'

markdown_extensions:
      - fontawesome_markdown
      - admonition
theme: 
  name: material
  logo: 'images/mansur_logo_noText.png'
  icon: 'images/mansur_logo_noText.png'
  favicon: 'images/mansur_logo_noText.png'
  palette:
    scheme: default
    primary: grey
    accent: grey

  features:
    - navigation.tabs
    - navigation.sections

  text: 'Ubuntu'
  code: 'Ubuntu Mono'
plugins:
    - search
extra:
  social:
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/MansurRig'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/asaf-b'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/channel/UCMjNlJjSxIam--3u87oh5PQ'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/mansurRig'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/asaf-ben-zur/'
    - icon: 'fontawesome/brands/imdb'
      link: 'https://www.imdb.com/name/nm8262040/?ref_=nv_sr_3'
    - icon: 'fontawesome/brands/instagram'
      link: 'https://www.instagram.com/mansurrig/'
    - icon: 'fontawesome/brands/artstation'
      link: 'https://www.artstation.com/mansur-rig'
nav:
    - index.md
    - About:
      - about.md
    - Support-Us:
      - Support-Us.md
    - User-Guides:
      - Getting-Started:
        - userGuides/System-Requirements.md
        - userGuides/installation.md
        - userGuides/Log-In.md
        - userGuides/Version-Updates.md
        - userGuides/Naming-Convention.md
        - userGuides/Asset-Scaling.md
        - userGuides/license.md
      - Tutorials:
        - Mansur-Rig 101:
          - userGuides/tutorials/mansurRig101/Introduction.md
          - userGuides/tutorials/mansurRig101/The-Basics.md
          - userGuides/tutorials/mansurRig101/Getting-Started.md
          - userGuides/tutorials/mansurRig101/Building-The-Leg-And-Foot.md
          - userGuides/tutorials/mansurRig101/Building-The-Arm-And-Fingers.md
          - userGuides/tutorials/mansurRig101/Completing-The-Guide-Template.md
          - userGuides/tutorials/mansurRig101/Puppet-Finish.md
          - userGuides/tutorials/mansurRig101/Conclusion.md
    - Help-Desk:
      - https://mansurrig.freshdesk.com/support/home
    - Release-Notes:
      - releaseNotes/v1.1.7.md
      - releaseNotes/v1.1.6.md
      - releaseNotes/v1.1.5.md
      - releaseNotes/v1.1.4.md
      - releaseNotes/v1.1.3.md
      - releaseNotes/v1.1.2.md
      - releaseNotes/v1.1.1.md
      - releaseNotes/v1.1.0.md
      - releaseNotes/v1.0.14.md
      - releaseNotes/v1.0.13.md
      - releaseNotes/v1.0.12.md
      - releaseNotes/v1.0.11.md
      - releaseNotes/v1.0.10.md
      - releaseNotes/v1.0.9.md
      - releaseNotes/v1.0.8.md
      - releaseNotes/v1.0.7.md
      - releaseNotes/v1.0.6.md
      - releaseNotes/v1.0.5.md
      - releaseNotes/v1.0.4.md
      - releaseNotes/v1.0.3.md
      - releaseNotes/v1.0.2.md
      - releaseNotes/v1.0.1.md
      - releaseNotes/v1.0.0.md
    - Code Documentation:
      - Maya-Plugins.md
      - mansur:
        - core:
          - arguments.md
          - globals.md
          - log.md
          - meshUtility.md
          - nodes.md
          - prefixSuffix.md
          - skinUtility.md
          - string.md
          - UIUtils.md
          - utility.md
        - globalUtils:
          - defSearch:
            - defSearch.md
          - logViewer:
            - logviewer.md
          - dynUI.md
        - adminUtils:
          - documentationBuild:
            - docBuildMansur.md
          - pluginRelease:
            - pluginRelease.md
          - productRelease:
            - install:
              - install.md
            - productRelease.md
          - userManagement:
            - userManagement.md
        - block:
          - cnsTool:
            - cnsTool.md
          - core:
            - Core_Module_Settings.md
            - blockUtility.md
            - buildModules.md
            - controlShapes.md
          - modules:
            - character_body:
              - foot:
                - foot_settings.md
                - foot.md
              - limb:
                - limb_settings.md
                - limb.md
              - meta:
                - meta_settings.md
                - meta.md
            - character_face:
              - curveZipB:
                - curveZipB_settings.md
                - curveZipB.md
              - lips:
                - lips_settings.md
                - lips.md
            - general:
              - FKChain:
                - FKChain_settings.md
                - FKChain.md
              - freeControl:
                - freeControl_settings.md
                - freeControl.md
              - lookAtControl:
                - lookAtControl_settings.md
                - lookAtControl.md
              - simpleSquash:
                - simpleSquash_settings.md
                - simpleSquash.md
          - moduleVisUI:
            - moduleVisUI.md
          - picker:
            - picker.md
            - plgSettings.md
          - blockBuildUI.md
extra_css:
    - extra.css

