site_name: 'Mansur-Rig - Documentation'
site_description: 'Documentation for the Mansur project, including the mansurPlugins library'
site_author: 'Assaf Ben Zur'

markdown_extensions:
      - fontawesome_markdown
      - admonition
      - attr_list
      - pymdownx.tabbed
      - pymdownx.superfences
theme: 
  name: material
  logo: 'images/mansur_logo_noText.png'
  icon: 'images/mansur_logo_noText.png'
  favicon: 'images/mansur_logo_noText.png'
  palette:
    scheme: default
    primary: grey
    accent: grey

  features:
    - navigation.tabs
    - navigation.sections

  text: 'Ubuntu'
  code: 'Ubuntu Mono'
plugins:
    - search
extra:
  social:
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.gg/nXfy3Rh5y6'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/channel/UCMjNlJjSxIam--3u87oh5PQ'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/MansurRig2'
    - icon: 'fontawesome/brands/artstation'
      link: 'https://www.linkedin.com/company/mansur-rig'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/asaf-b'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/mansurRig'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/asaf-ben-zur/'
    - icon: 'fontawesome/brands/imdb'
      link: 'https://www.imdb.com/name/nm8262040/?ref_=nv_sr_3'
    - icon: 'fontawesome/brands/instagram'
      link: 'https://www.instagram.com/mansurrig/'
nav:
    - index.md
    - About:
      - about.md
    - Support-Us:
      - Support-Us.md
    - User-Guides:
      - Getting-Started:
        - userGuides/System-Requirements.md
        - userGuides/installation.md
        - userGuides/Log-In.md
        - userGuides/License-Management.md
        - userGuides/Version-Updates.md
        - userGuides/Naming-Convention.md
        - userGuides/Asset-Scaling.md
        - userGuides/license.md
      - Rigging-Tools:
        - userGuides/Module-Preset-Editor.md
        - userGuides/IK-FK-Match.md
        - userGuides/Volume-Joints.md
        - userGuides/Scripted-Builds.md
        - userGuides/LODs-Tool.md
      - Animation-Tools:
        - userGuides/The-Picker.md
        - userGuides/Spaces-IK-FK-Tool.md
        - userGuides/Mocap-And-Game-Tools.md
        - userGuides/Spring-Tool.md
        - userGuides/CNS-Tool.md
      - Tutorials:
        - Mansur-Rig 101:
          - userGuides/tutorials/mansurRig101/01_Introduction.md
          - userGuides/tutorials/mansurRig101/02_The-Basics.md
          - userGuides/tutorials/mansurRig101/03_Getting-Started.md
          - userGuides/tutorials/mansurRig101/04_Building-The-Leg-And-Foot.md
          - userGuides/tutorials/mansurRig101/05_Building-The-Arm-And-Fingers.md
          - userGuides/tutorials/mansurRig101/06_Completing-The-Guides.md
          - userGuides/tutorials/mansurRig101/07_Puppet-Finish.md
          - userGuides/tutorials/mansurRig101/08_Conclusion.md
        - Mansur-Rig - Facial Rigging:
          - userGuides/tutorials/mansurRig_FacialRigging/01_Intro.md
          - userGuides/tutorials/mansurRig_FacialRigging/02_Rigging-The-Eyes.md
          - userGuides/tutorials/mansurRig_FacialRigging/03_Rigging-The-Eyelids.md
          - userGuides/tutorials/mansurRig_FacialRigging/04_Rigging-The-Eyelashes.md
          - userGuides/tutorials/mansurRig_FacialRigging/05_Finalizing-The-Eye.md
          - userGuides/tutorials/mansurRig_FacialRigging/06_Rigging-The-Eyebrows.md
          - userGuides/tutorials/mansurRig_FacialRigging/07_Nose-And-Cheek-Rig.md
          - userGuides/tutorials/mansurRig_FacialRigging/08_Rigging-The_Mouth.md
          - userGuides/tutorials/mansurRig_FacialRigging/09_Tweakers-And-Symmetry.md
          - userGuides/tutorials/mansurRig_FacialRigging/10_Finalizing-The-Rig.md
        - userGuides/tutorials/Variable-FK-Tail.md
        - userGuides/tutorials/Creating-A-Picker.md
    - Help-Desk:
      - https://mansurrig.freshdesk.com/support/home
    - Release-Notes:
      - releaseNotes/v2.2.0.md
      - releaseNotes/v2.1.0.md
      - releaseNotes/v2.0.0.md
      - releaseNotes/v1.5.2.md
      - releaseNotes/v1.5.1.md
      - releaseNotes/v1.5.0.md
      - releaseNotes/v1.4.6.md
      - releaseNotes/v1.4.5.md
      - releaseNotes/v1.4.4.md
      - releaseNotes/v1.4.3.md
      - releaseNotes/v1.4.2.md
      - releaseNotes/v1.4.1.md
      - releaseNotes/v1.4.0.md
      - releaseNotes/v1.3.6.md
      - releaseNotes/v1.3.5.md
      - releaseNotes/v1.3.4.md
      - releaseNotes/v1.3.2.md
      - releaseNotes/v1.3.1.md
      - releaseNotes/v1.3.0.md
      - releaseNotes/v1.2.3.md
      - releaseNotes/v1.2.2.md
      - releaseNotes/v1.2.1.md
      - releaseNotes/v1.2.0.md
      - releaseNotes/v1.1.9.md
      - releaseNotes/v1.1.7.md
      - releaseNotes/v1.1.6.md
      - releaseNotes/v1.1.5.md
      - releaseNotes/v1.1.4.md
      - releaseNotes/v1.1.3.md
      - releaseNotes/v1.1.2.md
      - releaseNotes/v1.1.1.md
      - releaseNotes/v1.1.0.md
    - Code Documentation:
      - Maya-Plugins.md
      - mansur:
        - core:
          - arguments.md
          - globals.md
          - log.md
          - meshUtility.md
          - nodes.md
          - prefixSuffix.md
          - skinUtility.md
          - string.md
          - UIUtils.md
          - utility.md
        - globalUtils:
          - defSearch:
            - defSearch.md
          - facialMocap:
            - facialMocapUtils.md
            - mnsFacialMocapTool.md
          - dynUI.md
        - adminUtils:
          - documentationBuild:
            - docBuildMansur.md
          - pluginRelease:
            - pluginRelease.md
          - productRelease:
            - install:
              - install.md
            - productRelease.md
        - block:
          - characterDefenition:
            - characterDefenitionUI.md
          - cnsTool:
            - cnsTool.md
          - core:
            - Core_Module_Settings.md
            - blockUtility.md
            - buildModules.md
            - controlShapes.md
          - LODsTool:
            - LODsTool.md
          - modulePresetEditor:
            - modulePresetEditor.md
          - modules:
            - character_body:
              - foot:
                - foot_settings.md
                - foot.md
              - hindLimb:
                - hindLimb_settings.md
                - hindLimb.md
              - limb:
                - limb_settings.md
                - limb.md
              - meta:
                - meta_settings.md
                - meta.md
              - wing:
                - wing_settings.md
                - wing.md
            - character_face:
              - curveZipB:
                - curveZipB_settings.md
                - curveZipB.md
              - lipsB:
                - lipsB_settings.md
                - lipsB.md
            - general:
              - curveAttachment:
                - curveAttachment_settings.md
                - curveAttachment.md
              - FKChain:
                - FKChain_settings.md
                - FKChain.md
              - freeControl:
                - freeControl_settings.md
                - freeControl.md
              - localClump:
                - localClump_settings.md
                - localClump.md
              - lookAtControl:
                - lookAtControl_settings.md
                - lookAtControl.md
              - simpleSquash:
                - simpleSquash_settings.md
                - simpleSquash.md
            - legacy:
              - curveZip:
                - curveZip_settings.md
                - curveZip.md
              - lips:
                - lips_settings.md
                - lips.md
            - mechanical:
              - chassis:
                - chassis_settings.md
                - chassis.md
              - hydraulicPiston:
                - hydraulicPiston_settings.md
                - hydraulicPiston.md
              - linkChain:
                - linkChain_settings.md
                - linkChain.md
              - sphereRoll:
                - sphereRoll_settings.md
                - sphereRoll.md
              - wheel:
                - wheel_settings.md
                - wheel.md
          - moduleVisUI:
            - moduleVisUI.md
          - picker2:
            - picker2.md
            - plgSettings.md
          - spacesTool:
            - mnsSpacesTool.md
          - springTool:
            - mnsSpringTool.md
          - volumeJointsUI:
            - volumeJointsUI.md
          - blockBuildUI.md
extra_css:
    - extra.css

